# Generated by Django 4.2.4 on 2023-09-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="menu_item_description",
            field=models.TextField(default="", max_length=1000),
        ),
    ]
