# Generated by Django 4.2.4 on 2023-08-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drinkscategory",
            name="description",
        ),
        migrations.AddField(
            model_name="drinks",
            name="price",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
