# Generated by Django 4.2.4 on 2023-08-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employees",
            name="shift",
            field=models.IntegerField(default=1),
        ),
    ]
