# Generated by Django 4.2.4 on 2023-08-26 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_employees_shift"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employees",
            old_name="full_name",
            new_name="first_name",
        ),
    ]
