# Generated by Django 4.2.4 on 2023-08-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("guest_count", models.IntegerField()),
                ("reservation_time", models.DateTimeField(auto_now=True)),
                ("comments", models.CharField(max_length=1000)),
            ],
        ),
    ]
